version: '3'

services:
  api:
    build: api
    environment:
      - DB_HOST=db
    ports:
      - 8080:8080
    networks:
      - demo-app
    depends_on:
      db:
        condition: service_healthy

  ui:
    build: ui
    ports:
      - 8081:80
    networks:
      - demo-app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - demo-app
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/0_init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

networks:
  demo-app: