CREATE USER 'keycloak'@'%' IDENTIFIED BY 'password';
CREATE DATABASE IF NOT EXISTS `dhbw` CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT ALL PRIVILEGES ON iwa.* TO `keycloak`@`%`;
USE dhbw;
CREATE TABLE people (id INT PRIMARY KEY, first_name TEXT, last_name TEXT, birthday TEXT, town TEXT, country TEXT, married TEXT);
INSERT INTO people VALUES(1,'Homer','Simpson','1959-04-20','Springfield','USA','Y');
INSERT INTO people VALUES(2,'Peter','Parker','1994-01-31','New York','USA','N');
INSERT INTO people VALUES(3,'Donald','Duck','1939-06-14','Entenhausen','USA','N');
INSERT INTO people VALUES(4,'Daisy','Duck','1941-09-22','Entenhausen','USA','N');
INSERT INTO people VALUES(5,'Max','Mustermann','1978-11-02','Musterhausen','Deutschland','Y');
INSERT INTO people VALUES(6,'Marta','Mustermann','1981-03-16','Musterhausen','Deutschland','Y');
INSERT INTO people VALUES(7,'Old','Shatterhand','1842-12-04','Silver City','USA','N');
INSERT INTO people VALUES(8,'Queen','Elizabeth','1926-04-21','London','Großbritannien','Y');
INSERT INTO people VALUES(9,'Prince','Philip','1921-06-10','London','Großbritannien','Y');
INSERT INTO people VALUES(10,'Crocodile','Dundee','1946-02-28','Sydney','Australien','N');
INSERT INTO people VALUES(11,'Väterchen','Frost','1951-05-29','Moskau','Russland','N');
INSERT INTO people VALUES(12,'Hans','Dampf','1964-08-16','Berlin','Deutschland','N');
INSERT INTO people VALUES(13,'Jon','Snow','1991-10-30','Winterfell','Westeros','N');
INSERT INTO people VALUES(14,'Marge','Simpsons','1962-11-08','Springfield','USA','Y');
INSERT INTO people VALUES(15,'Gustav','Eiffel','1876-08-11','Paris','Frankreich','Y');
INSERT INTO people VALUES(16,'Ping','Pong','2001-04-26','Peking','China','Y');
INSERT INTO people VALUES(17,'Ling','Pong','2000-01-13','Peking','China','Y');
INSERT INTO people VALUES(18,'Gustav','Gustavson','1987-06-12','Reykjavik','Island','Y');
INSERT INTO people VALUES(19,'Big','Foot','1971-07-07','Vancouver','Kanada','N');
INSERT INTO people VALUES(20,'Salvatore','Espresso','1975-05-06','Mailand','Italien','N');